### PR TITLE
Modernize and CMake project for Linux

### PR DESCRIPTION
**Pull request by bareya**
* clang formatting, don't use tabs
* `int64` type pulled from `SYS_Types.h`
* garbage CMake project file
* `std::string` swapped to `std::string&`
* `inline` functions outside of class

Remaining
 - [ ] CMake project dependent on `$HFS` variable and CMake distributed with Houdini
 - [ ] Current version is based on Flex 1.1 therefore it does not compile for version 2.0. Do a simple check to inform users about this limitation.

### CODE REVIEW

**Comment by bareya** [comment]
At free time I will keep rolling here to make it as a project that compiles on Linux machine.

**Comment by pedohorse** [comment]
there's no need to change code style
there's no need to replace pragma once with guards - msvc, gcc and clang support them

and plz fork and pull to development branch

**Comment by bareya** [comment]
using tabs in general is a bad idea.

**Comment by pedohorse** [comment]
* about tabs - it is just a matter of taste, there's nothing bad in it, until you have just cpp code at least. so the main question is - why care about it at all.
* pragma once is not standard, but it is a) ideologically superior to guards, b) is supported by all modern compilers, c) is not going anywhere in foreseeable future

**Pull request closed without merging**
